version: '3'
services:
  api:
    build: .
    command: bun run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      NODE_ENV: development