version: '3'
services:
  app:
    build: .
    command: bun run dev
    ports:
      - 3000:3000
    environment:
      PORT: 3000
    volumes:
      - .:/src/
      - nodemodules:/src/node_modules

volumes:
  nodemodules: {}